### ISSUE TITLE
Add compass heading channel

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#154] opened 2015-10-26 23:41 UTC
FormulaD would like to get compass heading in order to better calculate drift angles/info.

Also should add support to get this value in LuaScript.

**Comment by stieg** [comment] 2016-01-04 06:37
Dupe of #168 because the request is to get this channel for drift angle support.

**Closed by stieg** 2016-01-04 06:37 UTC
