### ISSUE TITLE
Send Cellular signal quality in telemetry stream

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#137] opened 2015-10-26 23:41 UTC
It would be useful to track signal strength and use it as a troubleshooting aid.  At a minimum it should be possible to send it as part of the device negotiation, although that'd be of limited value.

**Comment by stieg** [comment] 2016-01-04 18:20
Dupe of #138

**Closed by stieg** 2016-01-04 18:20 UTC
