### ISSUE TITLE
2nd wifi connection causes hard lock-up

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture-Pro_firmware#827] opened 2016-08-21 17:09 UTC
With firmware built as: RELEASE_TYPE=RELEASE_TYPE_BETA

I observe a hard lockup in RCT if a 2nd wifi client connects

STR:
Flash top of r/2.10.0
connect one wifi client
connect a second wifi client
observe firmware lock

Did not verify with MK2 yet.

**Comment by stieg** [comment] 2016-08-21 17:26
Is it locking up or going into panic?  If the latter how many flashes do you see.  Likely running out of RAM.

**Comment by brentpicasso** [comment] 2016-08-21 17:29
it locks up, no panic flashes.   Very reproducible with two command line launches of app

**Comment by stieg** [comment] 2016-08-21 17:34
Were you running a beta version (ie one without the extra checks) or a developer version?

**Comment by brentpicasso** [comment] 2016-08-21 17:37
I built it as: RELEASE_TYPE=RELEASE_TYPE_BETA

**Comment by stieg** [comment] 2016-08-23 18:09
Dupe of #797

**Closed by stieg** 2016-08-23 18:09 UTC
Labels: Bug, Duplicate
