### ISSUE TITLE
Investigate dropped usb connection for windows platform

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture-Pro_firmware#103] opened 2015-10-24 03:41 UTC
Observed on windows- USB device is dropped and re-enumerated sporadically. Observed in 2.8.5. Linux and OSX do not repro.

* Test against 2.8.4
* Check task priority changes in 2.8.5 to see if this caused a regression

**Comment by stieg** [comment] 2016-01-04 18:33
Dupe of #181

**Closed by stieg** 2016-01-04 18:33 UTC
Labels: Bug
