### ISSUE TITLE
RCT: periodic watchdog issue

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture-Pro_firmware#501] opened 2016-04-07 01:26 UTC
Periodically RCT will watchdog while simply transmitting data.  search and destroy

**Comment by stieg** [comment] 2016-04-07 01:27
No bueno.  Anything specific actions being taken or is it apparently random?

**Comment by brentpicasso** [comment] 2016-04-07 01:55
Unknown except that it happens.  A breakpoint will be the first step.

Brent Picasso
Autosport Labs
Technology for Race and Street

**Comment by stieg** [comment] 2016-06-05 18:45
Can't reproduce this.  Closing.

**Closed by stieg** 2016-06-05 18:45 UTC
Labels: Bug, RaceCapture, won't fix
