### ISSUE TITLE
Implement WiFi soft & hard reset support

### ISSUE THREAD

**Issue by stieg** [autosportlabs/RaceCapture-Pro_firmware#583] opened 2016-05-09 16:46 UTC
Needed for when we have to reset the WiFi device (which will happen).  Reset code also needs to be able to deal with system fallout and reset all proper state internally.

**Comment by brentpicasso** [comment] 2016-05-09 16:47
partial dupe of #507  (hardware reset aspect)

**Comment by brentpicasso** [comment] 2016-05-09 18:37
RCT will have control of the reset line for the wifi module. It is wired on PA5.

To reset, pull PA5 to active low. for normal operation, set to active high.

**Closed** 2016-06-09 23:42 UTC
Labels: Enhancement, Kickstarter Deliverable
