### ISSUE TITLE
Allow the ability to specify a full OBD-II PID request, for custom OEM specific PIDs

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture-Pro_firmware#167] opened 2015-10-26 23:42 UTC

**Comment by stieg** [comment] 2016-01-04 06:24
Seems very similar to #172.  Only difference is that #172 would need support to make a request first and the read the response.

**Comment by kosenko-max** [comment] 2016-04-02 19:33
Any milestone estimations?

**Comment by stieg** [comment] 2016-06-05 19:28
Closing as a dupe of #172.  We should implement this as part of that patch.

**Closed by stieg** 2016-06-05 19:28 UTC
Labels: duplicate, Enhancement
